//! Keywords are reserved keywords that help the parser interpret tokens and resolve ambiguities.
//! Some of the "keywords" here are actually just reserved words. They are reserved to avoid their
//! use as symbols in source files so that they can potentially be used in the future without
//! breaking existing code.

use std::collections::HashMap;

use lexing::tokens::Token;

pub fn new() -> HashMap<&'static str, Token> {
    let mut map = HashMap::new();
    map.extend(vec![
        ("_", Token::Ignore),
        ("as", Token::As),
        ("class", Token::Class),
        ("continue", Token::Continue),
        ("default", Token::Default),
        ("else", Token::Else),
        ("embed", Token::Embed),
        ("extend", Token::Extend),
        ("extends", Token::Extends),
        ("exports", Token::Exports),
        ("do", Token::Do),
        ("for", Token::For),
        ("if", Token::If),
        ("it", Token::ReservedKeyword),
        ("ignorable", Token::Ignorable),
        ("implements", Token::Implements),
        ("import", Token::Import),
        ("internal", Token::Internal),
        ("interface", Token::Interface),
        ("module", Token::Module),
        ("override", Token::Override),
        ("package", Token::Package),
        ("reject", Token::Reject),
        ("requires", Token::Requires),
        ("select", Token::Select),
        ("super", Token::Super),
        ("switch", Token::Switch),
        ("try", Token::Try),
        ("throw", Token::Throw),
        ("timeout", Token::Timeout),
        ("using", Token::Using),
        ("var", Token::Var),
        ("where", Token::Where),
        ("with", Token::With),
        ("while", Token::While),
        //
        // Reserved but not used.
        //
        ("asm", Token::ReservedKeyword),
        ("align", Token::ReservedKeyword),
        ("arena", Token::ReservedKeyword),
        ("atom", Token::ReservedKeyword),
        ("blittable", Token::ReservedKeyword),
        ("catch", Token::ReservedKeyword),
        ("co", Token::ReservedKeyword),
        ("checked", Token::ReservedKeyword),
        ("derives", Token::ReservedKeyword),
        ("diverging", Token::ReservedKeyword),
        ("disasm", Token::ReservedKeyword),
        ("dyn", Token::ReservedKeyword),
        ("dynamic", Token::ReservedKeyword),
        ("extern", Token::ReservedKeyword),
        ("fexpr", Token::ReservedKeyword),
        ("fixed", Token::ReservedKeyword),
        ("forall", Token::ReservedKeyword),
        ("gc", Token::ReservedKeyword),
        ("gen", Token::ReservedKeyword),
        ("get", Token::Get),
        ("in", Token::ReservedKeyword),
        ("link", Token::ReservedKeyword),
        ("llvm", Token::ReservedKeyword),
        ("macro", Token::ReservedKeyword),
        ("mut", Token::ReservedKeyword),
        ("mutating", Token::ReservedKeyword),
        ("nogc", Token::ReservedKeyword),
        ("noyield", Token::ReservedKeyword),
        ("operator", Token::ReservedKeyword),
        ("pack", Token::ReservedKeyword),
        ("pin", Token::ReservedKeyword),
        ("platform", Token::ReservedKeyword),
        ("pure", Token::ReservedKeyword),
        ("pragma", Token::ReservedKeyword),
        ("quasiquote", Token::ReservedKeyword),
        ("quote", Token::ReservedKeyword),
        ("reader", Token::ReservedKeyword),
        ("ref", Token::ReservedKeyword),
        ("stackalloc", Token::ReservedKeyword),
        ("seq", Token::ReservedKeyword),
        ("struct", Token::ReservedKeyword),
        ("sync", Token::ReservedKeyword),
        ("throws", Token::ReservedKeyword),
        ("total", Token::ReservedKeyword),
        ("transient", Token::ReservedKeyword),
        ("unchecked", Token::ReservedKeyword),
        ("unsafe", Token::ReservedKeyword),
        ("unquote", Token::ReservedKeyword),
        ("unllvm", Token::ReservedKeyword),
        ("yield", Token::ReservedKeyword),
        ("value", Token::ReservedKeyword),
        ("with", Token::ReservedKeyword),
    ]);
    map
}
