use std::collections::HashMap;

use lexing::tokens::Token;

pub fn new() -> HashMap<&'static str, Token> {
    let mut map = HashMap::new();
    map.extend(vec![
        ("_", Token::Ignore),
        ("as", Token::As),
        ("class", Token::Class),
        ("continue", Token::Continue),
        ("default", Token::Default),
        ("do", Token::Do),
        ("else", Token::Else),
        ("embeds", Token::Embeds),
        ("extend", Token::Extend),
        ("extends", Token::Extends),
        ("for", Token::For),
        ("get", Token::Get),
        ("if", Token::If),
        ("ignorable", Token::Ignorable),
        ("implements", Token::Implements),
        ("import", Token::Import),
        ("internal", Token::Internal),
        ("interface", Token::Interface),
        ("module", Token::Module),
        ("override", Token::Override),
        ("package", Token::Package),
        ("reject", Token::Reject),
        ("requires", Token::Requires),
        ("select", Token::Select),
        ("super", Token::Super),
        ("switch", Token::Switch),
        ("throw", Token::Throw),
        ("timeout", Token::Timeout),
        ("var", Token::Var),
        ("where", Token::Where),
        ("virtual", Token::Virtual),
        //
        // Reserved but not used.
        //
        ("atom", Token::ReservedKeyword),
        ("arena", Token::ReservedKeyword),
        ("blittable", Token::ReservedKeyword),
        ("case", Token::ReservedKeyword),
        ("catch", Token::ReservedKeyword),
        ("checked", Token::ReservedKeyword),
        ("defer", Token::ReservedKeyword),
        ("data", Token::ReservedKeyword),
        ("derives", Token::ReservedKeyword),
        ("disasm", Token::ReservedKeyword),
        ("dyn", Token::ReservedKeyword),
        ("dynamic", Token::ReservedKeyword),
        ("extern", Token::ReservedKeyword),
        ("exports", Token::ReservedKeyword),
        ("finally", Token::ReservedKeyword),
        ("fixed", Token::ReservedKeyword),
        ("ffi", Token::ReservedKeyword),
        ("foreign", Token::ReservedKeyword),
        ("forall", Token::ReservedKeyword),
        ("gc", Token::ReservedKeyword),
        ("in", Token::ReservedKeyword),
        ("implement", Token::ReservedKeyword),
        ("it", Token::ReservedKeyword),
        ("macro", Token::ReservedKeyword),
        ("mutating", Token::ReservedKeyword),
        ("mutable", Token::ReservedKeyword),
        ("mutate", Token::ReservedKeyword),
        ("native", Token::ReservedKeyword),
        ("nogc", Token::ReservedKeyword),
        ("operator", Token::ReservedKeyword),
        ("pattern", Token::ReservedKeyword),
        ("pure", Token::ReservedKeyword),
        ("pragma", Token::ReservedKeyword),
        ("quasiquote", Token::ReservedKeyword),
        ("quote", Token::ReservedKeyword),
        ("reader", Token::ReservedKeyword),
        ("ref", Token::ReservedKeyword),
        ("stackalloc", Token::ReservedKeyword),
        ("static", Token::ReservedKeyword),
        ("seq", Token::ReservedKeyword),
        ("struct", Token::ReservedKeyword),
        ("sync", Token::ReservedKeyword),
        ("total", Token::ReservedKeyword),
        ("transient", Token::ReservedKeyword),
        ("try", Token::ReservedKeyword),
        ("then", Token::ReservedKeyword),
        ("unchecked", Token::ReservedKeyword),
        ("unsafe", Token::ReservedKeyword),
        ("unquote", Token::ReservedKeyword),
        ("use", Token::ReservedKeyword),
        ("using", Token::ReservedKeyword),
        ("yield", Token::ReservedKeyword),
        ("value", Token::ReservedKeyword),
    ]);
    map
}
