image: docker:19.03.8

services:
  - docker:dind

build-stable:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

    - docker build --target sylan-build -t build .
    - docker build --target sylan-coverage -t coverage .

    - docker run --rm -v "$PWD:/opt/sylan" build
    - docker run --rm --security-opt seccomp=unconfined -v "$PWD":/opt/sylan coverage

  artifacts:
    reports:
      cobertura: cobertura.xml
