image: docker:19.03.8

services:
  - docker:dind

build-stable:
  stage: build
  script:
    - docker build --target rust-base -t rust-base .

    - docker build --target build -t build .
    - docker run --rm -v "$PWD:/opt/sylan" build

    - docker build --target coverage -t coverage .
    - docker run --rm --security-opt seccomp=unconfined -v "$PWD":/opt/sylan coverage
  artifacts:
    reports:
      cobertura: cobertura.xml

build-beta:
  stage: build
  script: docker build --target builder --build-arg RUST_CHANNEL=beta .
  rules:
    - allow_failure: true
