image: docker:19.03.8

services:
  - docker:dind

build-stable:
  stage: build
  script:
    - docker build --target coverage -t sylan-coverage .
    - mkdir coverage-results
    - docker run --rm --security-opt seccomp=unconfined -v "$PWD/coverage-results":/opt/coverage-results sylan-coverage
  artifacts:
    reports:
      cobertura: coverage-results/cobertura.xml

build-beta:
  stage: build
  script: docker build --target builder --build-arg RUST_CHANNEL=beta .
  rules:
    - allow_failure: true

