image: docker:19.03.8

services:
  - docker:dind

before_script:
  - apk add curl

build-stable:
  stage: build
  script:
    - docker build --target coverage -t sylan-coverage .
    - curl -LOSfs https://codecov.io/env
    - docker run --rm --security-opt seccomp=unconfined $(sh env) sylan-coverage
    - rm env

build-beta:
  stage: build
  script: docker build --target builder --build-arg RUST_CHANNEL=beta .
  rules:
    - allow_failure: true

