language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
git:
  depth: 1
  quiet: true
  submodules: false
before_script:
  - rustup component add rustfmt clippy
script:
  - cargo fmt --all -- --check
  - cargo clippy --all-targets --all-features -- -D warnings
  - RUSTFLAGS="-D warnings" cargo build
  - cargo test 
