[package]
name = "sylan"
version = "0.1.0"
authors = ["Louis Jackman <LouisJackman@users.noreply.github.com>"]
edition = "2018"
rust = "1.42"

[dependencies]

[profile.release]
panic = "abort"
lto = "fat"
codegen-units = 1

