version: 2

jobs:
  build:
    docker:
      - image: circleci/rust

    steps:
      - setup_remote_docker
      - checkout

      - run:
          name: Verify, Build and Upload Coverage for Stable Rust
          command: |
            docker build --target coverage -t sylan-coverage .
            ci_env=$(bash <(curl -s https://codecov.io/env))
            docker run --rm --security-opt seccomp=unconfined $ci_env sylan-coverage

      - run:
          name: Verify and Build for Beta Rust
          command: docker build --target builder --build-arg RUST_CHANNEL=beta .

