version: 2

jobs:
  build:
    docker:
      - image: circleci/rust

    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Verify and Build on Stable
          command: |
              rustup install stable
              make
      - run:
          name: Verify and Build on Beta
          command: |
              rustup install beta
              make RUST_VERSION=beta
      - run:
          name: Upload Coverage
          command: ./scripts/codecov.sh
      - save_cache:
          key: project-cache
          paths:
            - ./kcov-build/usr/local/bin/kcov
            - ./.codecov
            - "~/.cargo"
            - "~/.rustup"
            - "./target"

