version: 2

jobs:
  build:
    docker:
      - image: circleci/rust

    environment:
      DEBIAN_FRONTEND=noninteractive

    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Ensure kcov is Installed
          command: if ! [ -f /usr/bin/kcov ]; then apt-get install --yes --no-install-recommends kcov || exit 1; fi
      - run:
          name: Verify and Build on Stable
          command: |
              rustup install stable
              make
      - run:
          name: Verify and Build on Beta
          command: |
              rustup install beta
              make RUST_VERSION=beta
      - run:
          name: Upload Coverage
          command: ./scripts/codecov.sh
      - save_cache:
          key: project-cache
          paths:
            - "/usr/bin/kcov"
            - "~/.cargo"
            - "~/.rustup"
            - "./target"

